### ISSUE TITLE
using from python interpreter

### ISSUE THREAD

**Issue by triton7** [ayeowch/traceroute#2]
It seems that 'sources.json' should be parsed not only in the "main" function.
<pre>
>>> from traceroute import Traceroute
>>> tr = Traceroute('8.8.8.8')
>>> tr.traceroute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "traceroute.py", line 77, in traceroute
    status_code, traceroute = self.get_traceroute_output()
  File "traceroute.py", line 99, in get_traceroute_output
    url = self.source['url']
TypeError: string indices must be integers, not str
</pre>

**Comment by ayeowch** [comment]
fixed with https://github.com/ayeowch/traceroute/commit/f418b800d6e7e665e49e8ba846a3ac3f0434df01
